### ISSUE TITLE
aws-sdk should be a dependency and not a dev dependency 

### ISSUE THREAD

**Issue by kidculli** [Cimpress-MCP/microservice-utilities.js#33]
authorizer.js requires aws-sdk. Module will fail to load if aws-sdk is not installed

**Comment by kidculli** [comment]
Or you could make it a peer dependency

**Comment by thoean** [comment]
The `authorizer.js` is meant to run inside a Lambda, which has the `aws-sdk` automatically provided. So to keep Lambda deployment sizes smaller, typically the `aws-sdk` is not included (that is, is a dev dependency).

Since this is a library, you're absolutely right. Making this a peer dependency is likely the best option.

Do you want to come up with a merge request?

**Comment by kidculli** [comment]
Sure I can open one. Well the main issue is the module exports the Authorizer module. If I just want to use the Platform client I don't really need AWS as a dependency. Therefore if want to use any of the other modules I still need the aws-sdk installed

**Comment by kidculli** [comment]
So maybe require the sdk in the authorizer's constructor ? So it will only throw if you try to instantiate an authorized without AWS sdk installed

**Comment by thoean** [comment]
Yes, that makes sense.

It's only used by a relatively recent addition in [`ensureApiKey`](https://github.com/Cimpress-MCP/microservice-utilities.js/blob/release/0.1/src/authorizer.js#L48). Potentially just require it in this method.

**Comment by kidculli** [comment]
Can someone review my pull request ?

**Comment by thoean** [comment]
I did - asking to have the commits signed. Approved otherwise. Is that something you can do?

**Comment by kidculli** [comment]
Was having issues signing my commits will try again later
